Color search entities
amosproj/amos-ss2021-project2-context-map pull request #268
Opened 2021-06-07 09:04 UTC by derwehr

This PR colorizes search entites, as part of #261

2021-06-07 16:04 UTC, joluj requested changes
Store implementation missing. I have written the solution basically everywhere so just copy it:D only slight adaptations necessary.

Rest is very clean and easy to understand.

2021-06-07 16:04 UTC, joluj commented on frontend/src/visualization/filtering/GreyScaleToggle.tsx
> +  );
use store + consitent naming
```suggestion
  const greyScale = useObservable(entityColorStore.getGreyScale());
```

later (lines 18-21) set it with:

```ts
   entityColorStore.setGreyScale(!greyScale);
```

2021-06-07 16:04 UTC, joluj commented on frontend/src/stores/colors/EntityColorStore.ts
> +  public getGreyScale(): boolean {
add a sentence of documentation

2021-06-07 21:25 UTC, derwehr commented on frontend/src/visualization/filtering/Filter.tsx
> +  const colorize = entityColorStore.getValue();
Would that be the same as using the following?
```suggestion
  const colorize = useObservable(
    entityColorStore.getState(),
    entityColorStore.getValue()
  );
```
This makes sure colorize can't be undefined, else i get a ts error when invoking colorize later.

2021-06-07 21:27 UTC, joluj commented on frontend/src/visualization/filtering/Filter.tsx
> +  const colorize = entityColorStore.getValue();
Yes, I forgot the initial value.

2021-06-07 22:18 UTC, derwehr commented
Now this throws a bunch of runtime errors :cry: , will try to resolve them tomorrow

2021-06-08 09:08 UTC, joluj commented
React/useState is behaves differently when called with an function. Maybe we should refactor EntityColorizer to be an object with a colourize function

2021-06-08 17:06 UTC, joluj approved these changes

2021-06-08 17:49 UTC, merged